<?php

$alunos = [
  ["nome" => "Ana Maria", "email" => "anamaria@escolatecnica.com.br", "telefone" => "34 998251001", "estado" => "SP", "curso" => "Eletrônica", "turno" => "manhã"],
  ["nome" => "Pedro Paulo", "email" => "pedropaulo@escolatecnica.com.br", "telefone" => "34 998251002", "estado" => "RJ", "curso" => "Mecânica", "turno" => "tarde"],
  ["nome" => "Mariana Silva", "email" => "marianasilva@escolatecnica.com.br", "telefone" => "34 998251003", "estado" => "MG", "curso" => "Informática", "turno" => "noite"],
  ["nome" => "Carlos Pereira", "email" => "carlospereira@escolatecnica.com.br", "telefone" => "34 998251004", "estado" => "BA", "curso" => "Eletrônica", "turno" => "manhã"],
  ["nome" => "Fernanda Oliveira", "email" => "fernandaoliveira@escolatecnica.com.br", "telefone" => "34 998251005", "estado" => "SP", "curso" => "Eletrotécnica", "turno" => "tarde"],
  ["nome" => "José Silva", "email" => "josesilva@escolatecnica.com.br", "telefone" => "34 998251006", "estado" => "RS", "curso" => "Automação", "turno" => "noite"],
  ["nome" => "Lucas Gomes", "email" => "lucasgomes@escolatecnica.com.br", "telefone" => "34 998251007", "estado" => "PR", "curso" => "Mecatrônica", "turno" => "manhã"],
  ["nome" => "Bruna Costa", "email" => "brunacosta@escolatecnica.com.br", "telefone" => "34 998251008", "estado" => "SC", "curso" => "Informática", "turno" => "tarde"],
  ["nome" => "Ricardo Sousa", "email" => "ricardosousa@escolatecnica.com.br", "telefone" => "34 998251009", "estado" => "PE", "curso" => "Eletrônica", "turno" => "noite"],
  ["nome" => "Isabela Lima", "email" => "isabelalima@escolatecnica.com.br", "telefone" => "34 998251010", "estado" => "CE", "curso" => "Eletrotécnica", "turno" => "manhã"],
  ["nome" => "Renato Souza", "email" => "renatosouza@escolatecnica.com.br", "telefone" => "34 998251011", "estado" => "PB", "curso" => "Informática", "turno" => "tarde"],
  ["nome" => "Camila Santos", "email" => "camilasantos@escolatecnica.com.br", "telefone" => "34 998251012", "estado" => "MA", "curso" => "Automação", "turno" => "noite"],
  ["nome" => "Felipe Alves", "email" => "felipealves@escolatecnica.com.br", "telefone" => "34 998251013", "estado" => "RN", "curso" => "Mecânica", "turno" => "manhã"],
  ["nome" => "Rafael Silva", "email" => "rafaelsilva@escolatecnica.com.br", "telefone" => "34 998251014", "estado" => "PI", "curso" => "Informática", "turno" => "tarde"],
  ["nome" => "Julia Santos", "email" => "juliasantos@escolatecnica.com.br", "telefone" => "34 998251015", "estado" => "TO", "curso" => "Eletrotécnica", "turno" => "noite"],
  ["nome" => "Victor Carvalho", "email" => "victorcarvalho@escolatecnica.com.br", "telefone" => "34 998251016", "estado" => "GO", "curso" => "Mecatrônica", "turno" => "manhã"],
  ["nome" => "Daniela Borges", "email" => "danielaborges@escolatecnica.com.br", "telefone" => "34 998251017", "estado" => "AM", "curso" => "Automação", "turno" => "tarde"],
  ["nome" => "Henrique Vieira", "email" => "henriquevieira@escolatecnica.com.br", "telefone" => "34 998251018", "estado" => "RR", "curso" => "Eletrônica", "turno" => "noite"],
  ["nome" => "Tatiane Farias", "email" => "tatianefarias@escolatecnica.com.br", "telefone" => "34 998251019", "estado" => "AC", "curso" => "Informática", "turno" => "manhã"],
  ["nome" => "Rodrigo Monteiro", "email" => "rodrigomonteiro@escolatecnica.com.br", "telefone" => "34 998251020", "estado" => "AP", "curso" => "Mecânica", "turno" => "tarde"],
  ["nome" => "Paula Almeida", "email" => "paulaalmeida@escolatecnica.com.br", "telefone" => "34 998251021", "estado" => "RO", "curso" => "Eletrônica", "turno" => "manhã"],
  ["nome" => "Mateus Silva", "email" => "mateussilva@escolatecnica.com.br", "telefone" => "34 998251022", "estado" => "MS", "curso" => "Mecatrônica", "turno" => "tarde"],
  ["nome" => "Luana Pereira", "email" => "luanapereira@escolatecnica.com.br", "telefone" => "34 998251023", "estado" => "PA", "curso" => "Informática", "turno" => "noite"],
  ["nome" => "Thiago Andrade", "email" => "thiagoandrade@escolatecnica.com.br", "telefone" => "34 998251024", "estado" => "AL", "curso" => "Automação", "turno" => "manhã"],
  ["nome" => "Priscila Rocha", "email" => "priscilarocha@escolatecnica.com.br", "telefone" => "34 998251025", "estado" => "SE", "curso" => "Eletrotécnica", "turno" => "tarde"],
  ["nome" => "Eduardo Neves", "email" => "eduardoneves@escolatecnica.com.br", "telefone" => "34 998251026", "estado" => "ES", "curso" => "Eletrônica", "turno" => "noite"],
  ["nome" => "Larissa Cardoso", "email" => "larissacardoso@escolatecnica.com.br", "telefone" => "34 998251027", "estado" => "DF", "curso" => "Mecânica", "turno" => "manhã"],
  ["nome" => "Bruno Mendes", "email" => "brunomendes@escolatecnica.com.br", "telefone" => "34 998251028", "estado" => "RJ", "curso" => "Informática", "turno" => "tarde"],
  ["nome" => "Sara Carvalho", "email" => "saracarvalho@escolatecnica.com.br", "telefone" => "34 998251029", "estado" => "MT", "curso" => "Eletrotécnica", "turno" => "noite"],
  ["nome" => "Fabio Lopes", "email" => "fabiolopes@escolatecnica.com.br", "telefone" => "34 998251030", "estado" => "RS", "curso" => "Mecatrônica", "turno" => "manhã"],
  ["nome" => "Patricia Teixeira", "email" => "patriciateixeira@escolatecnica.com.br", "telefone" => "34 998251031", "estado" => "SP", "curso" => "Automação", "turno" => "tarde"],
  ["nome" => "Vinicius Oliveira", "email" => "viniciusoliveira@escolatecnica.com.br", "telefone" => "34 998251032", "estado" => "MG", "curso" => "Eletrônica", "turno" => "noite"],
  ["nome" => "Aline Barros", "email" => "alinebarros@escolatecnica.com.br", "telefone" => "34 998251033", "estado" => "BA", "curso" => "Informática", "turno" => "manhã"],
  ["nome" => "Juliana Moraes", "email" => "julianamoraes@escolatecnica.com.br", "telefone" => "34 998251034", "estado" => "GO", "curso" => "Eletrotécnica", "turno" => "tarde"],
  ["nome" => "Samuel Martins", "email" => "samuelmartins@escolatecnica.com.br", "telefone" => "34 998251035", "estado" => "AM", "curso" => "Mecânica", "turno" => "noite"],
  ["nome" => "Daniel Lima", "email" => "daniellima@escolatecnica.com.br", "telefone" => "34 998251036", "estado" => "RR", "curso" => "Eletrônica", "turno" => "manhã"],
  ["nome" => "Clara Ribeiro", "email" => "clararibeiro@escolatecnica.com.br", "telefone" => "34 998251037", "estado" => "AC", "curso" => "Automação", "turno" => "tarde"],
  ["nome" => "Leonardo Nunes", "email" => "leonardonunes@escolatecnica.com.br", "telefone" => "34 998251038", "estado" => "AP", "curso" => "Eletrotécnica", "turno" => "noite"],
  ["nome" => "Beatriz Araujo", "email" => "beatrizaraujo@escolatecnica.com.br", "telefone" => "34 998251039", "estado" => "RO", "curso" => "Informática", "turno" => "manhã"],
  ["nome" => "Wagner Santos", "email" => "wagnersantos@escolatecnica.com.br", "telefone" => "34 998251040", "estado" => "MS", "curso" => "Mecatrônica", "turno" => "tarde"],
  ["nome" => "Cristina Costa", "email" => "cristinacosta@escolatecnica.com.br", "telefone" => "34 998251041", "estado" => "PA", "curso" => "Mecânica", "turno" => "noite"],
  ["nome" => "Rodrigo Souza", "email" => "rodrigosouza@escolatecnica.com.br", "telefone" => "34 998251042", "estado" => "AL", "curso" => "Automação", "turno" => "manhã"],
  ["nome" => "Ana Paula Mendes", "email" => "anapaulamendes@escolatecnica.com.br", "telefone" => "34 998251043", "estado" => "SE", "curso" => "Eletrônica", "turno" => "tarde"],
  ["nome" => "Marcos Faria", "email" => "marcosfaria@escolatecnica.com.br", "telefone" => "34 998251044", "estado" => "ES", "curso" => "Informática", "turno" => "noite"],
  ["nome" => "Sofia Lima", "email" => "sofialima@escolatecnica.com.br", "telefone" => "34 998251045", "estado" => "DF", "curso" => "Mecatrônica", "turno" => "manhã"],
  ["nome" => "Antonio Ferreira", "email" => "antonioferreira@escolatecnica.com.br", "telefone" => "34 998251046", "estado" => "MT", "curso" => "Eletrotécnica", "turno" => "tarde"],
  ["nome" => "Gabriela Mota", "email" => "gabrielamota@escolatecnica.com.br", "telefone" => "34 998251047", "estado" => "TO", "curso" => "Automação", "turno" => "noite"]
];
